### ISSUE TITLE
Discarded oversize message

### ISSUE THREAD

**Issue by alacalcasis** [MISTLab/BuzzKH4#5]
Hello, I'm trying to use neighbors.broadcast to send a float number but the message is discarded for its size. I don't understand why:
1. the message id is just one character, which I suppose equals one byte
2. i suppose the float number is just 4 bytes
3. I don't know how much the sender id might be, but 2 bytes seems to me more than enough for names like k0, k1, k2...(as I've specified on argos file)

thus, the message is no more than 7 bytes, so I don't understand why the LogErr shows the following message: 
[k?] Discarded oversize message (16 bytes). Max size is 8 bytes.

Thank you in advance for any help, cheers!

Alan

**Comment by vivek-shankar** [comment]
Hai Alan, 

In buzz, a series of messages from different programming constructs are serialized to form one big block of message. As a buzz programmer, you will have to specify the max message size of this big block of messages. Based on the available message size the Buzz Virtual Machine optimizes to send the most important messages first.
As a result of this serialization, certain headers are added to disguise and deserialize the different types of messages. For instance, the header includes the type of message (Broadcast, virtual stigmergy put/get, and etc.) and the size of the current message. If you want to know more specifics on these you will have to look into the implementation of the Buzz Virtual Machine or the white paper on Buzz.

To give you a bit more idea on why your message is not fitting the max size you specified, the broadcast message format is MSG_SIZE(2 bytes) + MSG_TYPE(1 Byte)+ Topic(if a string, 2 bytes for the length of the string  + size of string) + Value (4 bytes). Apart from this, the sender id is added once in the message which will be 2 bytes. 

My recommendation is that as a Buzz programmer you could refer to the specifics a bit and use a rough estimate on the size of the message. This should also reflect your actual hardware limitation, for instance, Xbee's have a frame payload of approx. 250 bytes.   

If you have further questions feel free to contact me.

-Vivek

**Comment by alacalcasis** [comment]
Thank you Vivek. What I need is that kheperas share their yaw with neighbors, thus i've used:

neighbors.broadcast("y",pose.position["yaw"])

any suggestion on how to do it instead? Best regards,

Alan

**Comment by vivek-shankar** [comment]
You will have to increase the message size to realize this. You could increase the rab data size size by adding the following keyword while you specify your robots in your Argos file: ```<kheperaiv id="khiv" rab_range="10" rab_data_size="500" >``` 
This change should be made in this line https://github.com/ilpincy/argos3-kheperaiv/blob/master/src/testing/testbuzzexperiment.argos#L82
One more comment, the yaw should be accessed like the following: pose.orientation.yaw, if you use pose.position.yaw, it should most likely be nil, there is no value for the key yaw in the position table. 
I would recommend you to use the log function and inspect the values before you use them.  

-Vivek

**Comment by alacalcasis** [comment]
Thank you very much Vivek!! And yes, that is what I do, try out first with the log, but pose.position["yaw"] actually worked, that is, i am getting the same results as with pose.position.yaw.
Is there a document that describe all the options we can specify in an argos file?

**Comment by vivek-shankar** [comment]
ARGoS comes with an inbuilt query mechanism, you could query argos by using the -q flag and the entity you are querying for. 
For instance, if you want to know all the options for kheperaiv robot you can run the following command: ```argos3 -q kheperaiv```
This applies to any entity, sensor, or actuator.
