### ISSUE TITLE
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles". 

### ISSUE THREAD

**Issue by alacalcasis** [MISTLab/BuzzKH4#6]
Two months ago i did install BuzzKH4 on  my Mac with Ubuntu on VirtualBox. As long as I remember everything went ok. 

Now I'm trying to install it directly on an Ubuntu work station but get this error message:

$ cmake -DCMAKE_TOOLCHAIN_FILE=cmake/TargetKheperaIV.cmake ../src/

CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/home/acalderon/Descargas/BuzzKH4/build/CMakeFiles/CMakeOutput.log".

And I did verify cmake version with $ cmake --version obtaining:

cmake version 3.16.3

I found that cmake version on my Mac is 3.10.2, could this be the reason for the error I'm getting now? In such case, how should install procedure be updated?

**Comment by beltrame** [comment]
It seems you don't have your build-essentials installed, you are missing "make", not "cmake"

**Comment by alacalcasis** [comment]
Thank you for your answer, but I did 
make --version
and got
GNU Make 4.2.1

**Comment by vivek-shankar** [comment]
Are you building it for the khepera? If yes, you will have to setup your cross compiler environment. It is missing all the build essentials for the yocto distribution not your computers.  
You are using the yocto toolchain build file by using this file TargetKheperaIV.cmake and hence you will have to make sure your crosscompiling environment is set up. Otherwise you will have to build it onboard the khepera which is a very slow process and you might also run out of memory. 

If you want to check if the yocto toolchain gcc compiler exisits you can check that by using: 
```
$ /usr/local/khepera4-yocto/build/tmp/sysroots/i686-linux/usr/bin/armv7a-vfp-neon-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc --version
```
and you will get something like this:

arm-poky-linux-gnueabi-gcc (GCC) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by alacalcasis** [comment]
Hello, thank you for your answer. I was just trying to install khepera-iv to make simulations in Argos3. I am not working with khepera-iv physically, just virtually through argos3. I did install it in my MacBook weeks ago through an Ubuntu Virtual Box, but now I'm getting this error, did something changed in the instructions?

**Comment by ilpincy** [comment]
We updated ARGoS to beta57.

**Comment by alacalcasis** [comment]
Thank you! Does it mean that there is a new khepera-iv - buzz software on this repository? And that the new one doesn't work with latest version of Argos? But problems were not with Argos interaction, it was just when trying to install it...

**Comment by vivek-shankar** [comment]
Did you happen to install the kheperaIV package for ARGoS? It can be cloned and installed from this repo: https://github.com/ilpincy/argos3-kheperaiv
If you are just using the kheperaIV model in the simulator you will not need this repo. 
This repo contains the packages to run buzz on the physical khepera IV robots.

**Comment by alacalcasis** [comment]
Hello, sorry because I couldn't answer before. And yes, I did install argos3-kheperaiv before trying to install this repo. I haven't install khepera4-yocto-light-kbX.Y.tar.bz2 because I believed that is only necessary if you want to download scripts to physical kheperas, which is not my case, I just want to simulate them through Argos3.

**Comment by alacalcasis** [comment]
Finally, with the administration support here at my faculty we discover there was something wrong in our installation which was the real cause of all problems. Thank you Vivek, Beltrame and Carlo for all your help. Everything is working ok now!
